import React from 'react';

export default class Home extends React.Component {
	constructor(props) {
		super(props);
		this.props = props;
  }

	render() {
		return (
      <div>
        <h2>Inicio</h2>
        <code>
          {JSON.stringify(this.props)}
        </code>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus egestas rutrum libero sit amet dignissim. Integer porttitor urna sed felis egestas malesuada. Vivamus elementum turpis neque, in tincidunt sem varius vel. Nulla sed nulla et quam malesuada gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque egestas sed odio quis pharetra. Duis lobortis dui justo, vel tempus risus tristique sit amet.</p>
        <p>Quisque sit amet ligula gravida, tincidunt lorem nec, sagittis odio. Donec a lacinia nibh. Ut eros velit, pulvinar eu ex vitae, porta convallis nibh. Suspendisse potenti. Nam quis consectetur mauris, vel suscipit lorem. Etiam a risus ac nunc commodo tincidunt. Morbi tincidunt volutpat efficitur. Suspendisse eu diam vel leo ultrices congue non in est. Curabitur sagittis vulputate nisl nec efficitur. Sed vehicula tempus dapibus. Duis volutpat lobortis massa a cursus. Morbi aliquet ornare diam, ac ultricies tellus ullamcorper a. Etiam vitae nisi in lorem tincidunt feugiat sit amet vitae metus. Phasellus non tristique nulla. Cras in neque justo.</p>
        <p>Etiam arcu ipsum, sollicitudin nec ex nec, tempus ultrices magna. Nam fermentum augue et turpis suscipit, quis hendrerit orci malesuada. Morbi dapibus interdum diam eu dignissim. Nulla venenatis erat id tortor ornare varius. Sed eget mauris dolor. Donec nec justo id libero pharetra blandit. Ut vestibulum enim sollicitudin, mollis nibh eu, ornare lorem. Sed bibendum tortor dui, ut euismod diam imperdiet ut. Nulla facilisi. Nam volutpat enim vel sapien ullamcorper imperdiet. Mauris eleifend eros vel nibh consequat, et commodo tortor tristique. In sed odio non ex finibus porta. Donec facilisis ipsum sit amet felis tincidunt, vel eleifend nulla laoreet. Curabitur dictum molestie tortor, at suscipit diam suscipit vel.</p>
        <p>Aenean vestibulum ex in dapibus sagittis. Donec placerat quam at purus tempus, a semper arcu posuere. Donec ullamcorper diam vitae sodales ullamcorper. Curabitur at faucibus lectus. Phasellus laoreet iaculis dapibus. Suspendisse in semper tortor. Aenean mauris magna, bibendum a sapien id, sagittis pellentesque elit. Nam quis vulputate libero. Praesent accumsan scelerisque est luctus consectetur.</p>
        <p>Nam nec nibh in justo vulputate vulputate. In urna purus, mollis id molestie vitae, consectetur vitae felis. In luctus nulla ac augue tincidunt hendrerit. Nullam eu venenatis odio, nec tristique augue. Phasellus tincidunt eros nec fringilla fringilla. Cras porta porttitor dolor, eget lobortis justo aliquet sed. Nullam iaculis mi lacus, id elementum eros feugiat sed. Curabitur vulputate mauris erat. Sed aliquet efficitur nunc, ac lacinia orci. Donec mollis viverra ullamcorper. Phasellus rhoncus orci sit amet pulvinar varius. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas ullamcorper pharetra quam, a congue nunc. Praesent luctus convallis metus, quis laoreet tortor varius eget.</p>
        <p>Nam eros est, ullamcorper eget nunc eu, euismod ultrices arcu. Duis sollicitudin dui eget mauris molestie tristique. Curabitur vel mauris vulputate, dignissim risus at, pharetra lacus. Maecenas hendrerit eros mi, id lobortis ipsum pellentesque at. Mauris ullamcorper tristique est. Suspendisse gravida eros vel mi suscipit luctus. Fusce gravida id augue in aliquam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
        <p>Nullam diam ex, vestibulum nec mollis nec, rutrum sit amet massa. Praesent in dolor tellus. Morbi ornare eget ex rutrum molestie. Sed laoreet magna sit amet ex tristique molestie. Sed erat tortor, mollis at rhoncus a, sollicitudin vitae tortor. Vivamus tincidunt rutrum justo non pharetra. Phasellus eu ligula sed dolor maximus eleifend. Pellentesque quis venenatis magna.</p>
        <p>Duis et tellus nibh. Curabitur vitae mauris vel felis condimentum tincidunt volutpat quis nulla. Mauris vel volutpat diam. Pellentesque vulputate sed nibh a tincidunt. Suspendisse quam sapien, maximus at viverra quis, mollis vitae nunc. Maecenas a molestie massa, quis tincidunt ligula. Maecenas maximus vehicula ipsum vel placerat. Nulla dictum scelerisque est, elementum vulputate libero tincidunt quis. Nam eget mauris sit amet magna ornare bibendum eu at ligula. Etiam lacinia efficitur augue at accumsan. Morbi luctus euismod interdum. Duis posuere, nisi quis convallis vehicula, lacus nisl pharetra sapien, et scelerisque orci nulla vitae mauris. Morbi id metus nec ante pellentesque aliquet. Morbi consequat auctor auctor. Integer eu vehicula mauris. Duis ultrices arcu eu odio rhoncus ultricies.</p>
        <p>Vestibulum a arcu a orci ultricies iaculis. Duis facilisis hendrerit libero, sit amet ultrices dolor malesuada eu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse ultrices sollicitudin ultrices. Vivamus ut diam consequat, finibus magna non, iaculis elit. In elit dolor, faucibus vitae cursus malesuada, tincidunt iaculis justo. Praesent aliquam quam libero, non aliquet sem condimentum et. Vivamus eget dictum lectus. Suspendisse sit amet augue quis eros semper malesuada nec eget lorem. Nunc feugiat vel lectus mattis volutpat. Etiam tristique nunc id egestas vulputate.</p>
        <p>Mauris porta justo nisi, nec convallis quam sagittis id. Aliquam a tempus nibh. Donec nec massa arcu. In hac habitasse platea dictumst. Etiam euismod diam ut cursus semper. Vestibulum quis iaculis nisl, a molestie nulla. Morbi sollicitudin ipsum sit amet ex tempor pretium. Maecenas dictum luctus convallis. Suspendisse tristique, ante ut accumsan tincidunt, leo odio tincidunt eros, vitae sollicitudin nisl velit eu arcu. Pellentesque est magna, pulvinar eget ex eu, blandit mattis arcu. Phasellus congue nunc arcu, nec mattis magna molestie fermentum.</p>
        <p>Vivamus dolor sem, efficitur eu laoreet ut, eleifend sed ligula. Fusce volutpat elit risus, ac sollicitudin ligula bibendum vel. Vestibulum sollicitudin non lectus elementum aliquet. In a fermentum augue. Sed id leo orci. Curabitur sit amet metus est. Proin suscipit egestas nisi rutrum viverra. Suspendisse sed ex lectus.</p>
        <p>Proin suscipit, elit a finibus porta, magna justo blandit arcu, sed rhoncus dolor quam vitae ligula. Suspendisse dictum lobortis dolor at dignissim. Integer porta ultricies diam, in ultricies enim fermentum nec. Aliquam sed nisi velit. Maecenas tincidunt metus eu justo fermentum, id vestibulum nisi cursus. Fusce vehicula malesuada enim. Integer sollicitudin vestibulum sem vel congue.</p>
        <p>Nam convallis consequat enim et pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer condimentum, metus id varius vestibulum, ex lectus dignissim sem, at faucibus nisi turpis in eros. Integer eget ex in erat efficitur pulvinar. Sed rhoncus ante pharetra feugiat volutpat. Duis viverra ut magna eu condimentum. Sed posuere enim auctor tellus venenatis tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id suscipit tortor, ut porta mauris. Nulla quis sollicitudin odio, non pellentesque velit. Fusce facilisis feugiat felis. Mauris mattis quam mi, sit amet pretium dolor facilisis eget. Vivamus maximus tincidunt cursus.</p>
        <p>Proin lacinia pulvinar tellus efficitur cursus. Proin eu sollicitudin ipsum, id sodales ante. Cras quis tristique ligula, in commodo ex. Nunc volutpat efficitur rhoncus. Pellentesque porttitor feugiat quam, sit amet imperdiet nisl condimentum ut. Aliquam erat volutpat. Vestibulum maximus neque eget eros sodales lobortis. Cras dictum eros at risus mattis pharetra. Nunc aliquet mi eu condimentum laoreet. Fusce semper, mauris sed venenatis molestie, lectus justo interdum ipsum, non fringilla augue elit at odio. Phasellus efficitur placerat nulla. Donec nisi orci, tincidunt at quam eget, feugiat condimentum eros. Nunc facilisis ex urna, dapibus rutrum nisl pellentesque ut. Suspendisse congue ac mauris ut sodales. Integer finibus vel leo in sagittis. Sed sit amet felis rutrum, imperdiet libero tempor, eleifend augue.</p>
        <p>Integer massa nisl, dapibus vel imperdiet ut, cursus id velit. Sed purus felis, iaculis sed lacinia sit amet, iaculis ac velit. Nam faucibus risus nisl. Morbi ut odio at enim fermentum efficitur. Ut congue egestas leo, vitae egestas massa dictum nec. Nam scelerisque iaculis elit finibus mollis. Nunc faucibus ultricies vulputate. In hac habitasse platea dictumst.</p>
        <p>In in semper purus. Proin in dui metus. Sed vitae lorem at nisl venenatis condimentum. Fusce dignissim leo libero. In eleifend leo sit amet posuere pharetra. Nunc purus libero, ornare at porttitor sit amet, commodo ac diam. Quisque cursus blandit mauris, viverra iaculis sem condimentum sed. Donec aliquam nulla sollicitudin maximus rutrum. Pellentesque egestas at magna et viverra. Phasellus quis mauris dolor.</p>
        <p>Praesent pulvinar ut arcu convallis aliquam. Nam nisl libero, pharetra et ipsum non, hendrerit dapibus mauris. Phasellus lacus lectus, hendrerit at fringilla a, luctus a ante. Vivamus faucibus iaculis lacus, in faucibus ligula cursus nec. Vivamus ac volutpat neque, eu vestibulum nibh. Phasellus id dapibus massa. Morbi cursus et augue quis ornare. Vestibulum et libero nibh.</p>
        <p>Duis eget felis sed mi blandit euismod eget nec elit. Suspendisse blandit lectus ex, in tincidunt magna sagittis ac. Quisque eu risus eu velit vehicula hendrerit. Sed dictum gravida nulla. Suspendisse dignissim leo quis vehicula facilisis. Pellentesque non posuere augue. Integer et lacus at felis fermentum finibus. Etiam id purus justo. Maecenas porttitor enim vitae nunc venenatis, ac scelerisque turpis hendrerit.</p>
        <p>Suspendisse ac metus a erat semper malesuada id sed nisl. Pellentesque pharetra porta convallis. Vivamus mollis pharetra porta. Praesent finibus luctus mauris, at finibus orci. Duis lacinia dignissim odio ut malesuada. Fusce imperdiet molestie lectus, vel maximus mauris. Sed et condimentum neque. Curabitur congue elit mollis urna rhoncus cursus. Aenean non convallis tellus, in aliquet diam. Maecenas malesuada ornare orci, at eleifend orci elementum in. Maecenas accumsan quam ut erat cursus, sed viverra mi volutpat. Donec maximus at tortor vel eleifend.</p>
        <p>Duis vitae scelerisque dui. Curabitur et gravida ante, id mattis ipsum. Donec accumsan sapien a molestie convallis. Cras ut suscipit eros. Vivamus dolor lorem, dapibus vel nunc vitae, condimentum vehicula magna. Quisque eros sem, tincidunt at dolor sit amet, malesuada rutrum ipsum. Praesent faucibus, nisl ut aliquet finibus, odio metus vulputate turpis, quis cursus dui felis nec nisl. Phasellus nec erat eget velit dapibus elementum. Fusce fermentum viverra sapien. Nullam neque erat, volutpat sed molestie vehicula, fringilla sed dui. Nullam bibendum tempus sagittis.</p>
      </div>
		)
	}
}
